name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: dependencies
        run: bun install

      - name: lint
        run: bun run lint

      - name: typecheck
        run: bun run typecheck

      - name: unit test
        run: bun run test

      - name: integration test
        run: bun run test:integration
